services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - PROC_BASE=/host/proc
    ports:
      - "90:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro